### PR TITLE
better logging for id.wmo

### LINKED ISSUE #309: Id crashes if `DEBUG` isn't set to true
The ENV var `DEBUG` has to be true, or the server crashes.

### PR DESCRIPTION
**Pull request by cadecairos**
Fixes #309

### CODE REVIEW

File: web/server.js [hunk 1]
```diff
@@ -27,11 +27,33 @@ module.exports = function(options) {
...
+    server.register({
+      register: require('hapi-bunyan'),
+      options: {
+        logger: require('bunyan').createLogger({
+          name: 'id-webmaker-org',
+          level: options.logLevel
+        })
+      }
+    }, function(err) {
+      if ( err ) {
```
Comment (jbuck) [inline web/server.js]: `Hoek.assert()` instead perhaps?

**Comment by jbuck** [comment]
@cadecairos one suggestion, otherwise r+
