### PR TITLE
Design qa fixes

### LINKED ISSUE #101: Centre text vertically in fields
The text seems too low in the fields on both signup and login. Should move up by about 2-3px.
I am looking in FF 37 mac.

loginin-fieldtext
signup-fieldtext

### LINKED ISSUE #102: Make buttons 5px taller
I think the buttons need a bit more weight to them in relation to other elements on the forms. Would make them 5px taller.

### LINKED ISSUE #103: Move 'need help' link closer to the button
@alicoding and I played with this a bit but I think looking now that the 'need help' link needs to be a bit closer to the button by about 10px.

We may also need to replace the text with "Forgot password?", right @alicoding ?

need-help-link

### LINKED ISSUE #104: Decrease height of top blue bar
The top blue bar has a bit too much height to it. Let's decrease it by 10px. I'm measuring that it is 50px now, let's make it 40.

bluebarheight

### LINKED ISSUE #105: Field outlines should be #e2e2e2
Right now the borders on the fields on both Signup and Login are a tad dark. e2e2e2 should lighten it up.

### LINKED ISSUE #108: Move Headline on Signup up 70px
Right now the headline and subhead on Signup are sitting too low on the page. I'd recommend moving the text block up by about 70px. There should be about 60px from the top of the page to the top of the headline text, and 60px from the bottom of the headline to the top of the form.

signup-headline-up

### PR DESCRIPTION
**Pull request by secretrobotron**
fixes #102
fixes #105
fixes #108
fixes #101
fixes #103
fixes #104

### CODE REVIEW

File: templates/pages/login.jsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ var Login = React.createClass({
         <div className="loginPage innerForm centerDiv">
           <Form ref="userform" fields={fieldValues} validators={fieldValidators} />
           <button onClick={this.processFormData} className="btn btn-awsm">{buttonText}</button>
-          <Link to="reset-password" query={queryObj} className="need-help">Need help?</Link>
+          <Link to="reset-password" query={queryObj} className="need-help">Forgot password?</Link>
```
Comment (alicoding) [inline templates/pages/login.jsx]: Maybe change this to `Forgot your password?` ?

File: templates/less/styles.less [hunk 2]
```diff
@@ -48,7 +48,10 @@ h3 {
 
 .innerForm {
   text-align: center;
+  margin-top: initial;
```
Comment (alicoding) [inline templates/less/styles.less]: this will mess up the center of the div that we want on the page.

File: templates/less/styles.less [hunk 3]
```diff
@@ -48,7 +48,10 @@ h3 {
...
+
   @media (min-width : 451px) {
     text-align: right;
+    margin-top: 60px;
```
Comment (alicoding) [inline templates/less/styles.less]: and this.

**Comment by alicoding** [comment]
r+ with removing those two margin from `innerForm` and change the text accordingly.

**Comment by alicoding** [comment]
r+
